# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MakeComposites.py
# Created on: 2018-04-24 21:07:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
AST17042B4 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST17042B4"
AST17042B3 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST17042B3"
AST17042B2 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST17042B2"
AST17042B1 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST17042B1"
Prefire_composite_tif = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Prefire_composite.tif"
AST14506B4 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST14506B4"
AST14506B1 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST14506B1"
AST14506B2 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST14506B2"
AST14506B3 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST14506B3"
Postfire_composite_tif = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Postfire_composite.tif"

# Process: Composite Bands
arcpy.CompositeBands_management("X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST17042B4;X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST17042B3;X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST17042B2;X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST17042B1", Prefire_composite_tif)

# Process: Composite Bands (2)
arcpy.CompositeBands_management("X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST14506B4;X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST14506B1;X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST14506B2;X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\7\\data\\Schultz.gdb\\AST14506B3", Postfire_composite_tif)

