# ---------------------------------------------------------------------------
# Density_Model.py
# Created on: 2018-04-02 16:11:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: GSP 537 Sp 2018 Lab 6 Part 3
# John Bonifas
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Local variables:
FUFOO_Study = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\6\\data\\RasterMath.gdb\\FUFOO_Study"
Name = "Year2011"
Times_Kernel2 = ""
Times_Kernel1 = ""
Year2007 = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\6\\data\\RasterMath.gdb\\FUFOO_Study\\Year2011"
Kernel__Name_ = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\6\\data\\RasterMath.gdb\\Kernel_%Name%"
UFO__Name_ = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\6\\data\\RasterMath.gdb\\UFO_%Name%"

# Process: Iterate Feature Classes
arcpy.IterateFeatureClasses_mb(FUFOO_Study, "Year*", "POINT", "NOT_RECURSIVE")

# Process: Kernel Density
arcpy.gp.KernelDensity_sa(Year2007, "NONE", Kernel__Name_, "100", "", "SQUARE_MILES", "DENSITIES", "PLANAR")

# Process: Times
arcpy.gp.Times_sa("", "", Times_Kernel2)

# Process: Times (2)
arcpy.gp.Times_sa("", "", Times_Kernel1)

# Process: Int
arcpy.gp.Int_sa(Kernel__Name_, UFO__Name_)

