# ---------------------------------------------------------------------------
# RasterCalculator.py
# Created on: 2018-03-29 20:15:21.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: GSP 537 Sp 2018 Lab 6
# ---------------------------------------------------------------------------

Mean_UFO06_11_RasterCalculator = "X:\\Hostgator\\homework\\Courses\\GSP537\\labs\\6\\data\\RasterMath.gdb\\Mean_UFO06_11_RasterCalculator"
UFO_Year2006 = "Raster\\UFO_Year2006"
UFO_Year2007 = "Raster\\UFO_Year2007"
UFO_Year2008 = "Raster\\UFO_Year2008"
UFO_Year2009 = "Raster\\UFO_Year2009"
UFO_Year2010 = "Raster\\UFO_Year2010"
UFO_Year2011 = "Raster\\UFO_Year2011"
arcpy.gp.RasterCalculator_sa("(\"UFO_Year2006\" + \"UFO_Year2007\" + \"UFO_Year2008\" + \"UFO_Year2009\" + \"UFO_Year2010\" +  \"UFO_Year2011\") / 6", Mean_UFO06_11_RasterCalculator)

